### PR TITLE
A player has ships

### PR DESCRIPTION
**Pull request by lottetreg**
This is the first step towards being able to tie a tile on a board back to a specific ship (so we can announce "You've sunk your opponent's Destroyer!" when that happens).

A player should have ships, and a ship should have tiles (that's the next step).

### CODE REVIEW

**Comment by lottetreg** [comment]
> 👍 The diff in your player spec stood out to me. There were alot of changes required by adding a new dependency to this class. There might be a way to refactor this but I don't think it's a blocker, just something to think about.

@klkelley Thank you! I should have made it more clear in the PR comment, but most of the changes to the player spec were refactorings before I added the `ships` attribute. The only changes really brought about by adding `ships` was adding `ships: nil` to every `Ship` creation, and writing the new test for the `#ships` getter. Is that still too much change for adding this dependency? I'd love to know! Thank you so much for you feedback! :)

**Comment by klkelley** [comment]
I don't think it's too much of a change for adding a dependency.  It's just something to think about if you add a dependency to a class and find yourself having to make the same change in a bunch of places then there might be an opportunity to DRY things up. You'll almost always have to touch code/specs when you add a dependency but it's just a matter of how much you have to touch.

**Comment by lottetreg** [comment]
@klkelley I see! Thank you for that! I'll keep it in mind as I go along :)

**Comment by lottetreg** [comment]
Thank you @ecmendenhall for linking Thomas's article! That was very helpful. I made some changes based on the feedback: https://github.com/lottetreg/battleship-cli/pull/30/commits/5f604d705830a47df53cbc293347a9a76b6d39a4

**Pull request merged**
